name: Construir y Publicar Imagen Docker de la Web

on:
  push:
    branches:
      - main # Este workflow se activa cada vez que hay un push a la rama 'main'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest # Ejecutamos este trabajo en una máquina virtual Linux
    permissions:
      contents: read
      packages: write # Necesitamos permisos para publicar en GitHub Packages

    steps:
      - name: Clonar el Repositorio
        uses: actions/checkout@v4 # Acción para obtener el código del repositorio

      - name: Iniciar Sesión en GitHub Container Registry
        uses: docker/login-action@v3 # Acción oficial para login en Docker
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # Usa el usuario que activó el workflow
          password: ${{ secrets.GITHUB_TOKEN }} # Un token automático y seguro de GitHub

      - name: Construir y Publicar Imagen Docker
        uses: docker/build-push-action@v5 # Acción para construir y subir la imagen
        with:
          context: . # Busca el Dockerfile en el directorio actual
          push: true
          tags: ghcr.io/${{ github.repository }}:latest # Define la etiqueta de la imagen (nombre-repo:latest)
